### ISSUE TITLE
About linear combination Parameters in the target domain training α

### ISSUE THREAD

**Issue by Ruriiiii01** [grilled-chicken-burger/bci#1]
Hello,author,in your article, you mentioned the use of linear combination parameters α during the training process of the target domain model. May I ask if the initial α values are assigned randomly?

**Comment by grilled-chicken-burger** [comment]
是的。Thanks for your interest in my work.

**Comment by grilled-chicken-burger** [comment]
是的。Thanks for your interest in my work.
